// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-7XJsJCtyeglMZxaWjUvNUp8OZ01BLlg',
    appId: '1:978604178023:web:8c1b30a7432d8895d232c2',
    messagingSenderId: '978604178023',
    projectId: 'taskapp-4ee73',
    authDomain: 'taskapp-4ee73.firebaseapp.com',
    storageBucket: 'taskapp-4ee73.appspot.com',
    measurementId: 'G-X0KZEFJQZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKpJiRDs-VwoL_gJs2vYpJWxlpt3d6WBg',
    appId: '1:978604178023:android:94a4f6888c806d75d232c2',
    messagingSenderId: '978604178023',
    projectId: 'taskapp-4ee73',
    storageBucket: 'taskapp-4ee73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlohfUs7zxgxOsXVnRzy2BBbRn4MXKaNk',
    appId: '1:978604178023:ios:493fd4fcde9913a7d232c2',
    messagingSenderId: '978604178023',
    projectId: 'taskapp-4ee73',
    storageBucket: 'taskapp-4ee73.appspot.com',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlohfUs7zxgxOsXVnRzy2BBbRn4MXKaNk',
    appId: '1:978604178023:ios:2032b843630ca5dad232c2',
    messagingSenderId: '978604178023',
    projectId: 'taskapp-4ee73',
    storageBucket: 'taskapp-4ee73.appspot.com',
    iosBundleId: 'com.example.tp2.RunnerTests',
  );
}
